# 🚀 GPT

In this notebook, we'll walk through the steps required to train your own GPT model on the wine review dataset

The code is adapted from the excellent [GPT tutorial](https://keras.io/examples/generative/text_generation_with_miniature_gpt/) created by Apoorv Nandan available on the Keras website.

In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import json
import re
import string
from IPython.display import display, HTML

import tensorflow as tf
from tensorflow.keras import layers, models, losses, callbacks

## 0. Parameters <a name="parameters"></a>

In [2]:
VOCAB_SIZE = 10000
MAX_LEN = 80
EMBEDDING_DIM = 256
KEY_DIM = 256
N_HEADS = 2
FEED_FORWARD_DIM = 256
VALIDATION_SPLIT = 0.2
SEED = 42
LOAD_MODEL = False
BATCH_SIZE = 32
EPOCHS = 5

## 1. Load the data <a name="load"></a>

In [3]:
# Load the full dataset
with open("winemag-data-130k-v2.json") as json_data:
    wine_data = json.load(json_data)

In [4]:
wine_data[10]

{'points': '87',
 'title': 'Kirkland Signature 2011 Mountain Cuvée Cabernet Sauvignon (Napa Valley)',
 'description': 'Soft, supple plum envelopes an oaky structure in this Cabernet, supported by 15% Merlot. Coffee and chocolate complete the picture, finishing strong at the end, resulting in a value-priced wine of attractive flavor and immediate accessibility.',
 'taster_name': 'Virginie Boone',
 'taster_twitter_handle': '@vboone',
 'price': 19,
 'designation': 'Mountain Cuvée',
 'variety': 'Cabernet Sauvignon',
 'region_1': 'Napa Valley',
 'region_2': 'Napa',
 'province': 'California',
 'country': 'US',
 'winery': 'Kirkland Signature'}

In [5]:
# Filter the dataset
filtered_data = [
    "wine review : "
    + x["country"]
    + " : "
    + x["province"]
    + " : "
    + x["variety"]
    + " : "
    + x["description"]
    for x in wine_data
    if x["country"] is not None
    and x["province"] is not None
    and x["variety"] is not None
    and x["description"] is not None
]

In [6]:
# Count the recipes
n_wines = len(filtered_data)
print(f"{n_wines} recipes loaded")

129907 recipes loaded


In [7]:
example = filtered_data[25]
print(example)

wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard-designated Pinot that hails from a high-elevation site. Small in production, it offers intense, full-bodied raspberry and blackberry steeped in smoky spice and smooth texture.


## 2. Tokenize the data <a name="tokenize"></a>

In [8]:
# Pad the punctuation, to treat them as separate 'words'
def pad_punctuation(s):
    s = re.sub(f"([{string.punctuation}, '\n'])", r" \1 ", s)
    s = re.sub(" +", " ", s)
    return s


text_data = [pad_punctuation(x) for x in filtered_data]

In [9]:
# Display an example of a recipe
example_data = text_data[25]
example_data

'wine review : US : California : Pinot Noir : Oak and earth intermingle around robust aromas of wet forest floor in this vineyard - designated Pinot that hails from a high - elevation site . Small in production , it offers intense , full - bodied raspberry and blackberry steeped in smoky spice and smooth texture . '

In [13]:
# Convert to a Tensorflow Dataset
text_ds = (
    tf.data.Dataset.from_tensor_slices(text_data)
    .batch(BATCH_SIZE)
    .shuffle(1000)
)

In [14]:
# Create a vectorisation layer
vectorize_layer = layers.TextVectorization(
    standardize="lower",
    max_tokens=VOCAB_SIZE,
    output_mode="int",
    output_sequence_length=MAX_LEN + 1,
)

In [15]:
# Adapt the layer to the training set
vectorize_layer.adapt(text_ds)
vocab = vectorize_layer.get_vocabulary()

In [16]:
# Display some token:word mappings
for i, word in enumerate(vocab[:10]):
    print(f"{i}: {word}")

0: 
1: [UNK]
2: :
3: ,
4: .
5: and
6: the
7: wine
8: a
9: of


In [15]:
# Display the same example converted to ints
example_tokenised = vectorize_layer(example_data)
print(example_tokenised.numpy())

[   7   10    2   20    2   29    2   43   62    2   55    5  243 4145
  453  634   26    9  497  499  667   17   12  142   14 2214   43   25
 2484   32    8  223   14 2213  948    4  594   17  987    3   15   75
  237    3   64   14   82   97    5   74 2633   17  198   49    5  125
   77    4    0    0    0    0    0    0    0    0    0    0    0    0
    0    0    0    0    0    0    0    0    0    0    0]


## 3. Create the Training Set <a name="create"></a>

In [17]:
# Create the training set of recipes and the same text shifted by one word
def prepare_inputs(text):
    text = tf.expand_dims(text, -1)
    tokenized_sentences = vectorize_layer(text)
    x = tokenized_sentences[:, :-1]
    y = tokenized_sentences[:, 1:]
    ##print(x.numpy(),y.numpy())
    return x, y


train_ds = text_ds.map(prepare_inputs)

In [18]:
example_input_output = train_ds.take(1).get_single_element()

In [19]:
# Example Input
example_input_output[0][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([   7,   10,    2,   20,    2,   29,    2,   61,    2,  246,    5,
         38,  202,  193,    5,  257,   69,   26,  275,   46,    8, 1528,
         60,   17,   12,  251,    3,  185,  139,   83,    8,  108,    9,
         86,    4,    6,   28,   13,   91,  653,    3,   11, 3376,    5,
         95,   16,  415,   47,    8,  198,  110,    4,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int64)>

In [19]:
# Example Output (shifted by one token)
example_input_output[1][0]

<tf.Tensor: shape=(80,), dtype=int64, numpy=
array([  10,    2,  152,    2,  723,    2,  230,   24,    2,   17,   12,
         27,    9,  500,    5, 3549,    3,  347,  294, 2346,   24,   70,
          3,   68,   34,    5,   56,   14, 4648,   30,    4,   11,  416,
          1,   87,    3,   93,    1,    7,   13,  177,   19,   35,    4,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0], dtype=int64)>

## 5. Create the causal attention mask function <a name="causal"></a>

In [20]:
def causal_attention_mask(batch_size, n_dest, n_src, dtype):
    i = tf.range(n_dest)[:, None]
    j = tf.range(n_src)
    m = i >= j - n_src + n_dest
    mask = tf.cast(m, dtype)
    mask = tf.reshape(mask, [1, n_dest, n_src])
    mult = tf.concat(
        [tf.expand_dims(batch_size, -1), tf.constant([1, 1], dtype=tf.int32)], 0
    )
    return tf.tile(mask, mult)


np.transpose(causal_attention_mask(1, 10, 10, dtype=tf.int32)[0])

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 1, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 1, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

## 6. Create a Transformer Block layer <a name="transformer"></a>

In [21]:
class TransformerBlock(layers.Layer):
    def __init__(self, num_heads, key_dim, embed_dim, ff_dim, dropout_rate=0.1):
        super(TransformerBlock, self).__init__()
        self.num_heads = num_heads
        self.key_dim = key_dim
        self.embed_dim = embed_dim
        self.ff_dim = ff_dim
        self.dropout_rate = dropout_rate
        self.attn = layers.MultiHeadAttention(
            num_heads, key_dim, output_shape=embed_dim
        )
        self.dropout_1 = layers.Dropout(self.dropout_rate)
        self.ln_1 = layers.LayerNormalization(epsilon=1e-6)
        self.ffn_1 = layers.Dense(self.ff_dim, activation="relu")
        self.ffn_2 = layers.Dense(self.embed_dim)
        self.dropout_2 = layers.Dropout(self.dropout_rate)
        self.ln_2 = layers.LayerNormalization(epsilon=1e-6)

    def call(self, inputs):
        input_shape = tf.shape(inputs)
        batch_size = input_shape[0]
        seq_len = input_shape[1]
        causal_mask = causal_attention_mask(
            batch_size, seq_len, seq_len, tf.bool
        )
        attention_output, attention_scores = self.attn(
            inputs,
            inputs,
            attention_mask=causal_mask,
            return_attention_scores=True,
        )
        attention_output = self.dropout_1(attention_output)
        out1 = self.ln_1(inputs + attention_output)
        ffn_1 = self.ffn_1(out1)
        ffn_2 = self.ffn_2(ffn_1)
        ffn_output = self.dropout_2(ffn_2)
        return (self.ln_2(out1 + ffn_output), attention_scores)

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "key_dim": self.key_dim,
                "embed_dim": self.embed_dim,
                "num_heads": self.num_heads,
                "ff_dim": self.ff_dim,
                "dropout_rate": self.dropout_rate,
            }
        )
        return config

## 7. Create the Token and Position Embedding <a name="embedder"></a>

In [22]:
class TokenAndPositionEmbedding(layers.Layer):
    def __init__(self, max_len, vocab_size, embed_dim):
        super(TokenAndPositionEmbedding, self).__init__()
        self.max_len = max_len
        self.vocab_size = vocab_size
        self.embed_dim = embed_dim
        self.token_emb = layers.Embedding(
            input_dim=vocab_size, output_dim=embed_dim
        )
        self.pos_emb = layers.Embedding(input_dim=max_len, output_dim=embed_dim)

    def call(self, x):
        maxlen = tf.shape(x)[-1]
        positions = tf.range(start=0, limit=maxlen, delta=1)
        positions = self.pos_emb(positions)
        x = self.token_emb(x)
        return x + positions

    def get_config(self):
        config = super().get_config()
        config.update(
            {
                "max_len": self.max_len,
                "vocab_size": self.vocab_size,
                "embed_dim": self.embed_dim,
            }
        )
        return config

## 8. Build the Transformer model <a name="transformer_decoder"></a>

In [23]:
inputs = layers.Input(shape=(None,), dtype=tf.int32)
x = TokenAndPositionEmbedding(MAX_LEN, VOCAB_SIZE, EMBEDDING_DIM)(inputs)
x, attention_scores = TransformerBlock(
    N_HEADS, KEY_DIM, EMBEDDING_DIM, FEED_FORWARD_DIM
)(x)
outputs = layers.Dense(VOCAB_SIZE, activation="softmax")(x)
gpt = models.Model(inputs=inputs, outputs=[outputs, attention_scores])
gpt.compile("adam", loss=[losses.SparseCategoricalCrossentropy(), None])

In [24]:
gpt.summary()

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, None)                │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ token_and_position_embedding         │ (None, None, 256)           │       2,580,480 │
│ (TokenAndPositionEmbedding)          │                             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ transformer_block (TransformerBlock) │ [(None, None, 256), (None,  │         658,688 │
│                                      │ 2, None, None)]             │                 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, None, 10000)         │       2,570,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,809,168 (22.16 MB)

 Trainable params: 5,809,168 (22.16 MB)

 Non-trainable params: 0 (0.00 B)

In [25]:
if LOAD_MODEL:
    # model.load_weights('./models/model')
    gpt = models.load_model("./models/gpt", compile=True)

## 9. Train the Transformer <a name="train"></a>

In [26]:
# Create a TextGenerator checkpoint
class TextGenerator(callbacks.Callback):
    def __init__(self, index_to_word, top_k=10):
        self.index_to_word = index_to_word
        self.word_to_index = {
            word: index for index, word in enumerate(index_to_word)
        }

    def sample_from(self, probs, temperature):
        probs = probs ** (1 / temperature)
        probs = probs / np.sum(probs)
        return np.random.choice(len(probs), p=probs), probs

    def generate(self, start_prompt, max_tokens, temperature):
        start_tokens = [
            self.word_to_index.get(x, 1) for x in start_prompt.split()
        ]
        sample_token = None
        info = []
        while len(start_tokens) < max_tokens and sample_token != 0:
            x = np.array([start_tokens])
            y, att = self.model.predict(x, verbose=0)
            sample_token, probs = self.sample_from(y[0][-1], temperature)
            info.append(
                {
                    "prompt": start_prompt,
                    "word_probs": probs,
                    "atts": att[0, :, -1, :],
                }
            )
            start_tokens.append(sample_token)
            start_prompt = start_prompt + " " + self.index_to_word[sample_token]
        print(f"\ngenerated text:\n{start_prompt}\n")
        return info

    def on_epoch_end(self, epoch, logs=None):
        self.generate("wine review", max_tokens=80, temperature=1.0)

In [27]:
# Create a model save checkpoint
model_checkpoint_callback = callbacks.ModelCheckpoint(
    filepath="./checkpoint/checkpoint.ckpt.weights.h5",
    save_weights_only=True,
    save_freq="epoch",
    verbose=0,
)

tensorboard_callback = callbacks.TensorBoard(log_dir="./logs")

# Tokenize starting prompt
text_generator = TextGenerator(vocab)

In [28]:
gpt.fit(
    train_ds,
    epochs=EPOCHS,
    callbacks=[model_checkpoint_callback, tensorboard_callback, text_generator],
)

Epoch 1/5
4060/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 248ms/step - loss: 2.5944
generated text:
wine review : france : southwest france : tannat : a soft , spicy and sweet wine with some acidity , it feels lightly peppery and ripe and smooth . blueberry flavors are just right to their heady . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 1017s 249ms/step - loss: 2.5943
Epoch 2/5
4060/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 153ms/step - loss: 1.9799
generated text:
wine review : france : bordeaux : bordeaux - style red blend : [UNK] reserve [UNK] captures the concentrated , with tannins and this wine that ' s full of structured structure which is backed with a fine , tannic core . 

4060/4060 ━━━━━━━━━━━━━━━━━━━━ 624s 154ms/step - loss: 1.9799
Epoch 3/5
4060/4060 ━━━━━━━━━━━━━━━━━━━━ 0s 154ms/step - loss: 1.8979
generated text:
wine review : us : california : bordeaux - style red blend : 90 % cabernet franc and 10 % merlot , this is the opposite of the ripe red fruit and oak . the tannins are here , ripe and powerful bu

In [30]:
# Save the final model
gpt.save("./models/gpt.keras")

# 3. Generate text using the Transformer

In [31]:
def print_probs(info, vocab, top_k=5):
    for i in info:
        highlighted_text = []
        for word, att_score in zip(
            i["prompt"].split(), np.mean(i["atts"], axis=0)
        ):
            highlighted_text.append(
                '<span style="background-color:rgba(135,206,250,'
                + str(att_score / max(np.mean(i["atts"], axis=0)))
                + ');">'
                + word
                + "</span>"
            )
        highlighted_text = " ".join(highlighted_text)
        display(HTML(highlighted_text))

        word_probs = i["word_probs"]
        p_sorted = np.sort(word_probs)[::-1][:top_k]
        i_sorted = np.argsort(word_probs)[::-1][:top_k]
        for p, i in zip(p_sorted, i_sorted):
            print(f"{vocab[i]}:   \t{np.round(100*p,2)}%")
        print("--------\n")

In [32]:
info = text_generator.generate(
    "wine review : us", max_tokens=80, temperature=1.0
)


generated text:
wine review : us : washington : viognier : this is a peach - pit , melon and lemon candy aromas . lively and pleasing more pungent , with breathing time and shows pretty acid . melony fruit gains character with a pleasantly herbal twist , finishing in a swirl of orange . 



In [33]:
info = text_generator.generate(
    "wine review : italy", max_tokens=80, temperature=0.5
)


generated text:
wine review : italy : veneto : corvina , rondinella , molinara : this ripasso opens with a dark garnet color and ruby in the glass . it has a deep ruby color and a ruby appearance that shows a fresh and clean finish . 



In [34]:
info = text_generator.generate(
    "wine review : germany", max_tokens=80, temperature=0.5
)
print_probs(info, vocab)


generated text:
wine review : germany : rheinhessen : riesling : a touch of mineral clings to the palate of this dry , medium - bodied riesling . it ' s a bit lean , but it ' s a tad lean in style with a lemony , tart finish . 



::   	100.0%
-:   	0.0%
zealand:   	0.0%
grosso:   	0.0%
,:   	0.0%
--------



mosel:   	67.99%
rheinhessen:   	12.44%
nahe:   	9.24%
rheingau:   	8.94%
baden:   	0.72%
--------



::   	100.0%
other:   	0.0%
-:   	0.0%
valley:   	0.0%
[UNK]:   	0.0%
--------



riesling:   	98.19%
dornfelder:   	0.54%
pinot:   	0.45%
spätburgunder:   	0.4%
weissburgunder:   	0.21%
--------



::   	100.0%
-:   	0.0%
blanc:   	0.0%
grosso:   	0.0%
and:   	0.0%
--------



a:   	46.62%
the:   	11.07%
this:   	9.79%
sweet:   	6.13%
while:   	4.19%
--------



touch:   	20.78%
bit:   	20.06%
whiff:   	8.46%
little:   	3.25%
heady:   	3.2%
--------



of:   	98.74%
blossomy:   	0.23%
off:   	0.23%
overripe:   	0.14%
green:   	0.11%
--------



sweet:   	27.75%
smoke:   	15.98%
petrol:   	13.57%
sweetness:   	13.19%
honey:   	5.77%
--------



and:   	28.58%
tones:   	21.49%
oil:   	12.37%
on:   	10.24%
notes:   	6.51%
--------



to:   	100.0%
into:   	0.0%
through:   	0.0%
at:   	0.0%
on:   	0.0%
--------



the:   	88.72%
a:   	10.3%
an:   	0.23%
nose:   	0.17%
fresh:   	0.13%
--------



nose:   	66.21%
palate:   	31.34%
bouquet:   	0.57%
lemon:   	0.2%
fresh:   	0.19%
--------



of:   	97.66%
in:   	1.33%
on:   	0.84%
,:   	0.08%
for:   	0.05%
--------



this:   	99.77%
the:   	0.2%
a:   	0.02%
[UNK]:   	0.01%
riesling:   	0.0%
--------



dry:   	91.5%
off:   	3.6%
riesling:   	1.38%
intensely:   	0.66%
wine:   	0.55%
--------



,:   	77.15%
riesling:   	22.51%
wine:   	0.15%
and:   	0.09%
white:   	0.03%
--------



medium:   	78.64%
full:   	5.49%
invigorating:   	2.17%
tart:   	1.6%
refreshing:   	1.29%
--------



-:   	99.99%
bodied:   	0.0%
sweet:   	0.0%
dry:   	0.0%
straw:   	0.0%
--------



bodied:   	98.54%
sweet:   	1.33%
weight:   	0.08%
to:   	0.04%
dry:   	0.01%
--------



riesling:   	98.96%
wine:   	0.68%
white:   	0.14%
dry:   	0.1%
kabinett:   	0.07%
--------



.:   	99.71%
,:   	0.12%
that:   	0.11%
with:   	0.04%
which:   	0.01%
--------



it:   	86.03%
the:   	11.27%
a:   	0.42%
there:   	0.39%
dry:   	0.38%
--------



':   	99.96%
has:   	0.02%
finishes:   	0.02%
is:   	0.01%
offers:   	0.0%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
11:   	0.0%
off:   	0.0%
--------



a:   	22.15%
dry:   	12.83%
lean:   	5.74%
rich:   	4.9%
brisk:   	4.57%
--------



bit:   	84.52%
little:   	1.79%
tad:   	1.38%
delicate:   	0.97%
shade:   	0.96%
--------



lean:   	84.47%
austere:   	6.6%
angular:   	0.7%
sharp:   	0.58%
tart:   	0.58%
--------



,:   	49.68%
and:   	20.81%
in:   	15.11%
on:   	13.01%
but:   	0.91%
--------



but:   	62.96%
with:   	35.54%
and:   	0.51%
offering:   	0.22%
yet:   	0.19%
--------



it:   	34.68%
the:   	17.96%
quite:   	8.6%
also:   	5.52%
a:   	4.84%
--------



':   	81.84%
finishes:   	7.89%
is:   	3.17%
offers:   	1.66%
has:   	1.47%
--------



s:   	100.0%
ll:   	0.0%
[UNK]:   	0.0%
re:   	0.0%
nuanced:   	0.0%
--------



a:   	71.29%
also:   	7.79%
quite:   	3.45%
not:   	2.65%
an:   	2.17%
--------



bit:   	87.62%
pleasant:   	2.59%
tad:   	2.35%
little:   	2.04%
thirst:   	1.15%
--------



lean:   	37.26%
lacking:   	12.37%
more:   	8.26%
tart:   	8.17%
watery:   	7.72%
--------



in:   	35.73%
,:   	30.73%
on:   	20.76%
and:   	10.07%
.:   	1.38%
--------



style:   	77.39%
texture:   	12.43%
profile:   	4.2%
body:   	2.65%
feel:   	0.87%
--------



,:   	84.43%
with:   	13.19%
.:   	1.7%
and:   	0.4%
but:   	0.09%
--------



a:   	84.73%
tart:   	6.84%
lime:   	1.62%
brisk:   	0.95%
an:   	0.68%
--------



tart:   	22.4%
brisk:   	15.47%
lean:   	11.13%
slightly:   	5.27%
clean:   	3.36%
--------



finish:   	36.04%
acidity:   	29.93%
,:   	16.15%
kick:   	5.05%
acid:   	4.12%
--------



tart:   	28.97%
with:   	16.9%
but:   	12.2%
lime:   	9.89%
finishing:   	4.46%
--------



finish:   	42.97%
,:   	31.12%
lime:   	7.25%
lemon:   	6.39%
green:   	3.16%
--------



.:   	99.9%
that:   	0.08%
with:   	0.01%
,:   	0.01%
and:   	0.0%
--------



:   	98.66%
drink:   	1.2%
it:   	0.1%
a:   	0.01%
the:   	0.01%
--------

